"""Initial migration

Revision ID: 005105e4e01d
Revises: 
Create Date: 2026-07-08 21:11:54.326019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '005105e4e01d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctor', 'phone',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
    op.alter_column('doctor', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('doctor', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('doctor', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.alter_column('patient', 'phone',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
    op.alter_column('patient', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('patient', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('patient', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.alter_column('patient', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('patient', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('patient', 'phone',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
    op.alter_column('doctor', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.alter_column('doctor', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('doctor', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('doctor', 'phone',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
    # ### end Alembic commands ###
