"""Add appointments and doctor duty times

Revision ID: 82dcca37cb7a
Revises: 005105e4e01d
Create Date: 2026-07-09 19:24:11.225000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '82dcca37cb7a'
down_revision: Union[str, Sequence[str], None] = '005105e4e01d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('appointment', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.drop_constraint(op.f('appointment_ibfk_2'), 'appointment', type_='foreignkey')
    op.drop_constraint(op.f('appointment_ibfk_1'), 'appointment', type_='foreignkey')
    op.create_foreign_key(None, 'appointment', 'doctor', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'appointment', 'patient', ['patient_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.create_foreign_key(op.f('appointment_ibfk_1'), 'appointment', 'patient', ['patient_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('appointment_ibfk_2'), 'appointment', 'doctor', ['doctor_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('appointment', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.alter_column('appointment', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    # ### end Alembic commands ###
