# Generated by Django 4.2.16 on 2026-07-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='appointment',
        ),
        migrations.AlterModelTable(
            name='doctor',
            table='doctor',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patient',
        ),
    ]
